name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew releaseBundle

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: build/distributions

      - uses: armory-io/plugin-test-runner@main
        with: 
          service: ${{ github.event.client_payload.service }}
          version: ${{ github.event.client_payload.version }}
          plugin_sha: ${{ github.event.client_payload.sha }}
